var fs=require('fs')
// fs.mkdirSync('Hello')
fs.writeFileSync('Hello/data.txt','Hello')
fs.appendFileSync('Hello/data.txt','How are You?')
fs.renameSync('Hello/data.txt','Hello/user.txt')
var data=fs.readFileSync('Hello/user.txt','utf-8')
console.log(data)
fs.unlinkSync('Hello/user.txt')
fs.rmdirSync('Hello')
